In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Womens Clothing E-Commerce Reviews.csv')

In [3]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [5]:
df['Division Name'].unique()

array(['Initmates', 'General', 'General Petite', nan], dtype=object)

In [6]:
df['Department Name'].unique()

array(['Intimate', 'Dresses', 'Bottoms', 'Tops', 'Jackets', 'Trend', nan],
      dtype=object)

In [7]:
df['Division Name'].value_counts()

General           13850
General Petite     8120
Initmates          1502
Name: Division Name, dtype: int64

In [8]:
df['Department Name'].value_counts()

Tops        10468
Dresses      6319
Bottoms      3799
Intimate     1735
Jackets      1032
Trend         119
Name: Department Name, dtype: int64

In [9]:
df['Class Name'].value_counts()

Dresses           6319
Knits             4843
Blouses           3097
Sweaters          1428
Pants             1388
Jeans             1147
Fine gauge        1100
Skirts             945
Jackets            704
Lounge             691
Swim               350
Outerwear          328
Shorts             317
Sleep              228
Legwear            165
Intimates          154
Layering           146
Trend              119
Casual bottoms       2
Chemises             1
Name: Class Name, dtype: int64

# Label Encoding

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Division Name'] = le.fit_transform(df['Division Name'])
df['Department Name'] = le.fit_transform(df['Department Name'])
df['Class Name'] = le.fit_transform(df['Class Name'])

In [11]:
df['Division Name'].value_counts()

0    13850
1     8120
2     1502
3       14
Name: Division Name, dtype: int64

In [12]:
df['Department Name'].value_counts()

4    10468
1     6319
0     3799
2     1735
3     1032
5      119
6       14
Name: Department Name, dtype: int64

In [13]:
df['Class Name'].value_counts()

3     6319
8     4843
0     3097
17    1428
13    1388
7     1147
4     1100
15     945
6      704
11     691
18     350
12     328
14     317
16     228
10     165
5      154
9      146
19     119
20      14
1        2
2        1
Name: Class Name, dtype: int64

In [14]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count  Division Name  Department Name  Class Name  
0                        0              2                2           5  
1                        4              0                1           3  
2                        0              0                1           3  
3                        0              1                0          13  
4                        6              0                4           0

# Independent and Dependent

In [15]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [16]:
df.shape

(23486, 11)

In [17]:
df.drop(['Unnamed: 0','Clothing ID','Title','Review Text'],axis = 1,inplace = True)

In [18]:
df.head()

Age  Rating  Recommended IND  Positive Feedback Count  Division Name  \
0   33       4                1                        0              2   
1   34       5                1                        4              0   
2   60       3                0                        0              0   
3   50       5                1                        0              1   
4   47       5                1                        6              0   

   Department Name  Class Name  
0                2           5  
1                1           3  
2                1           3  
3                0          13  
4                4           0

In [19]:
df = df[['Age', 'Rating', 'Positive Feedback Count', 'Division Name', 'Department Name', 'Class Name', 'Recommended IND']]

In [20]:
df.head()

Age  Rating  Positive Feedback Count  Division Name  Department Name  \
0   33       4                        0              2                2   
1   34       5                        4              0                1   
2   60       3                        0              0                1   
3   50       5                        0              1                0   
4   47       5                        6              0                4   

   Class Name  Recommended IND  
0           5                1  
1           3                1  
2           3                0  
3          13                1  
4           0                1

In [21]:
y = df.iloc[:,6:]
y

Recommended IND
0                    1
1                    1
2                    0
3                    1
4                    1
...                ...
23481                1
23482                1
23483                0
23484                1
23485                1

[23486 rows x 1 columns]

In [22]:
x = df.iloc[:,0:5]
x

Age  Rating  Positive Feedback Count  Division Name  Department Name
0       33       4                        0              2                2
1       34       5                        4              0                1
2       60       3                        0              0                1
3       50       5                        0              1                0
4       47       5                        6              0                4
...    ...     ...                      ...            ...              ...
23481   34       5                        0              1                1
23482   48       3                        0              1                4
23483   31       3                        1              1                1
23484   28       3                        2              0                1
23485   52       5                       22              1                1

[23486 rows x 5 columns]

In [23]:
x = df.iloc[:,0:5].values
x

array([[33,  4,  0,  2,  2],
       [34,  5,  4,  0,  1],
       [60,  3,  0,  0,  1],
       ...,
       [31,  3,  1,  1,  1],
       [28,  3,  2,  0,  1],
       [52,  5, 22,  1,  1]], dtype=int64)

In [24]:
y = df.iloc[:,6:].values
y

array([[1],
       [1],
       [0],
       ...,
       [0],
       [1],
       [1]], dtype=int64)

# Train, Test and Split

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [26]:
import tensorflow as tf
tf.keras.utils.to_categorical

<function keras.utils.np_utils.to_categorical(y, num_classes=None, dtype='float32')>

In [27]:
y_train = tf.keras.utils.to_categorical(y_train, 20)
y_test = tf.keras.utils.to_categorical(y_test, 20)
#we need to convert y_test and y_train to ((y_train, 20)and(y_test, 20))because
#the shape must match with the result

In [28]:
x.shape

(23486, 5)

In [29]:
y.shape

(23486, 1)

In [30]:
x_train.shape

(18788, 5)

In [31]:
x_test.shape

(4698, 5)

In [32]:
y_train.shape

(18788, 20)

# Feature Scaling

In [33]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.transform(x_test)

In [34]:
x_train

array([[-0.66666886,  0.72410942, -0.09612312, -0.76750882, -0.83121347],
       [ 0.95786173,  0.72410942,  0.4196202 , -0.76750882,  1.00390271],
       [ 1.4452209 , -1.08236619, -0.439952  ,  2.4638538 , -0.21950808],
       ...,
       [-0.17930968, -1.08236619,  0.4196202 ,  0.84817249, -0.83121347],
       [ 0.06436991, -1.08236619, -0.439952  ,  0.84817249, -0.83121347],
       [ 0.22682296,  0.72410942, -0.439952  , -0.76750882,  1.00390271]])

In [35]:
x_test

array([[ 1.12031479, -0.17912838, -0.26803756,  0.84817249,  0.39219732],
       [ 1.36399438,  0.72410942,  0.07579132,  0.84817249,  1.00390271],
       [-0.66666886,  0.72410942, -0.439952  , -0.76750882,  1.00390271],
       ...,
       [-0.66666886, -1.98560399, -0.439952  , -0.76750882,  1.00390271],
       [ 1.20154132, -0.17912838, -0.09612312, -0.76750882,  1.00390271],
       [-0.42298927,  0.72410942, -0.439952  ,  0.84817249, -1.44291887]])

# Model Building

# Importing Libraries

In [36]:
import tensorflow as tf
import keras as ks

In [37]:
from keras.models import Sequential
from keras.layers import Dense

In [38]:
model = Sequential()

# Input Layer

In [39]:
model.add(Dense(units=10,kernel_initializer='random_uniform',activation='relu'))

# Hidden Layer

In [40]:
model.add(Dense(units=5,kernel_initializer='random_uniform',activation='relu'))

In [41]:
model.add(Dense(units=10,kernel_initializer='random_uniform',activation='relu'))

# Output Layer

In [42]:
model.add(Dense(units=20,kernel_initializer='random_uniform',activation='softmax'))

# Configuring Learning Process

In [43]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

# Fit the model

In [45]:
model.fit(x_train,y_train,epochs=20,batch_size=44)

Epoch 1/20
427/427 [==============================] - 1s 3ms/step - loss: 0.1430 - accuracy: 0.9352
Epoch 2/20
427/427 [==============================] - 1s 3ms/step - loss: 0.1431 - accuracy: 0.9355
Epoch 3/20
427/427 [==============================] - 1s 2ms/step - loss: 0.1426 - accuracy: 0.9363
Epoch 4/20
427/427 [==============================] - 1s 2ms/step - loss: 0.1422 - accuracy: 0.9366
Epoch 5/20
427/427 [==============================] - 1s 3ms/step - loss: 0.1425 - accuracy: 0.9370
Epoch 6/20
427/427 [==============================] - 1s 3ms/step - loss: 0.1423 - accuracy: 0.9358
Epoch 7/20
427/427 [==============================] - 1s 3ms/step - loss: 0.1424 - accuracy: 0.9368
Epoch 8/20
427/427 [==============================] - 1s 3ms/step - loss: 0.1423 - accuracy: 0.9365
Epoch 9/20
427/427 [==============================] - 1s 3ms/step - loss: 0.1422 - accuracy: 0.9359
Epoch 10/20
427/427 [==============================] - 1s 3ms/step - loss: 0.1420 - accuracy: 0.9360

# Test the Model

In [46]:
ypred = model.predict(x_test)

In [47]:
ypred

array([[2.0231124e-02, 9.7976893e-01, 1.2233141e-11, ..., 1.1317432e-11,
        1.2063991e-11, 1.7471601e-11],
       [9.7765774e-04, 9.9902236e-01, 4.0255088e-18, ..., 3.5485986e-18,
        3.8601459e-18, 7.0962667e-18],
       [1.6116827e-03, 9.9838829e-01, 4.8936753e-17, ..., 4.3498523e-17,
        4.7095776e-17, 8.3191209e-17],
       ...,
       [9.3691170e-01, 6.3081600e-02, 3.7781831e-07, ..., 3.9382920e-07,
        3.6113681e-07, 3.6214180e-07],
       [2.5712531e-02, 9.7428745e-01, 4.1951831e-11, ..., 3.8973699e-11,
        4.1432403e-11, 5.8829837e-11],
       [2.4915696e-03, 9.9750841e-01, 3.8175568e-16, ..., 3.4139909e-16,
        3.6985222e-16, 6.3233995e-16]], dtype=float32)

In [48]:
y_test

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [49]:
ypred = ypred>0.5
ypred

array([[False,  True, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       ...,
       [ True, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False]])

In [50]:
x_test[0]

array([ 1.12031479, -0.17912838, -0.26803756,  0.84817249,  0.39219732])

In [51]:
y_test[0]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)

In [52]:
predict = model.predict([[1.12031479, -0.17912838, -0.26803756,  0.84817249,  0.39219732]])

In [53]:
predict>0.5

array([[False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False]])